name: CI Pipeline

on:
  pull_request:
    types:
      - opened

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint
