name: Run and Check Tests

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    outputs:
      test-result: ${{ steps.run-tests.outputs.test-result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: run-tests
        run: npm run test

  check-tests:
    name: Check Test Results
    runs-on: ubuntu-latest

    needs: run-tests

    steps:
      - name: Check test results
        run: echo "${{ needs.run-tests.outputs.test-result }}"
